% Minimal preprocessing smoke test using the single ShapeNet sample bundled
% with the official PRS-Net repository.
%
% Run from MATLAB:
%   cd preprocess
%   addpath(genpath('C:\path\to\gptoolbox'))
%   run_smoke_preprocess

precomputeShapeData( ...
    './shapenet', ...
    '../datasets/shapenet', ...
    './data_split_smoke', ...
    {'02691156'}, ...
    1, ...
    1, ...
    1);
